### ISSUE TITLE
May want to make ModPerl::RegistryCooker a runtime recommends dependency

### ISSUE THREAD

**Issue by zmughal** [SunStarSys/sealed#1]
Instead of a `require` so that the `sealed.pm` functionality is tested and installable on more systems. Also possible to add as `optional_features` as done here: <https://metacpan.org/release/OETIKER/PDF-QRCode-0.1.1/source/Makefile.PL>, <https://github.com/oetiker/pdf-qrcode/pull/1/files>.

**Comment by joesuf4** [comment]
Great idea!  I mean, there's no real reason to pull the ModPerl::RegistryCooker dependency into this Makefile.PL, because nobody will test/use ModPerl::RegistryCookerSealed module in here unless they have mod_perl2.

**Comment by joesuf4** [comment]
Resolved in v4.3.0
